---
project_name: loop

archives:
  - id: loop
    files:
      - LICENSE
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    rlcp: true

brews:
  - name: loop
    caveats: ''
    commit_author:
      name: Kamil Samigullin
      email: kamil@samigullin.info
    description: Loom structure fetcher.
    folder: Formula
    homepage: https://github.com/tact-app/loop
    tap:
      owner: tact-app
      name: homebrew-tap
    install: |
      bin.install "loop"

      output = Utils.popen_read("#{bin}/loop completion bash")
      (bash_completion/loop).write output

      output = Utils.popen_read("#{bin}/loop completion fish")
      (fish_completion/loop.fish).write output

      output = Utils.popen_read("#{bin}/loop completion zsh")
      (zsh_completion/_loop).write output

      prefix.install_metafiles
    test: |
      system "#{bin}/loop version"

builds:
  - id: loop
    binary: loop
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    main: .

checksum: { name_template: checksums.txt }

release:
  github:
    owner: tact-app
    name: loop
