#!/usr/bin/env bash

[ "${BASH_VERSINFO:-0}" -ge 4 ] || {
  echo "bash version 4 or higher is required" >&2
  exit 1
}

set -euo pipefail

function dto() {
  cat tools/loom/responses/userWorkspaceMemberships.*.json |
    gojsonstruct \
      -packagename dto \
      -typename Workspaces \
      >internal/service/loom/dto/workspaces.go
  cat tools/loom/responses/GetMyClosedSpaceMemberships.*.json |
    gojsonstruct \
      -packagename dto \
      -typename PrivateSpaces \
      >internal/service/loom/dto/private_spaces.go
  cat tools/loom/responses/getOpenSpaces.*.json |
    gojsonstruct \
      -packagename dto \
      -typename PublicSpaces \
      >internal/service/loom/dto/public_spaces.go
  cat tools/loom/responses/GetWorkspaceArchivedSpaces.*.json |
    gojsonstruct \
      -packagename dto \
      -typename ArchivedSpaces \
      >internal/service/loom/dto/archived_spaces.go
  cat tools/loom/responses/GetPublishedFolders.*.json |
    gojsonstruct \
      -packagename dto \
      -typename Folders \
      >internal/service/loom/dto/folders.go
  make format
}

declare -A config
config['dryrun']=false

_() {
  if ${config['dryrun']}; then
    echo "${@}"
    return
  fi
  trap 'echo "${@}"' ERR
  "${@}"
}
@debug() { echo "${@}"; }
@trace() { @debug "${@}" && "${@}"; }
@error() { echo "${@}" >&2; }
@fatal() { @error "${@}" && exit 1; }
@usage() {
  cat - <<EOF
Usage: $0 <task> <args>
Tasks:
EOF
  compgen -A function | grep -Ev '^(@|_)' | sort | cat -n
}

function @main() {
  if [[ "${1:-}" =~ ^--dry-run|-d$ ]]; then
    config['dryrun']=true
    shift
  fi
  "${@:-@usage}"
}

@main "${@}"
