query userWorkspaceMemberships {
    userWorkspaceMemberships {
        member_role
        createdAt
        organization {
            id
            name
            type
            limits
            counts {
                videos
                screenshots
                users
                folders
                spaces {
                    total_active_spaces
                }
            }
            member_roles {
                value
                name
                inviteable
                is_free
            }
        }
    }
}
