query GetWorkspaceArchivedSpaces(
    $first: Int!
    $after: String
) {
    result: getWorkspaceArchivedSpaces {
        ... on GetWorkspaceArchivedSpacesPayload {
            spaces(first: $first, after: $after) {
                nodes {
                    id
                    name
                    workspace_id
                    privacy
                    is_primary
                    totalVideos
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
        ... on Error {
            message
        }
    }
}
