query GetMyClosedSpaceMemberships(
    $first: Int!
    $after: String
) {
    result: getMyClosedSpaceMemberships {
        ... on GetMyClosedSpaceMembershipsPayload {
            memberships(first: $first, after: $after) {
                edges {
                    node {
                        id
                        space {
                            id
                            name
                            workspace_id
                            privacy
                            is_primary
                            totalVideos
                        }
                    }
                }
                pageInfo {
                    endCursor
                    hasNextPage
                }
            }
        }
        ... on Error {
            message
        }
    }
}
