# @name GetParentFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetParentFolders.json

###

# @name GetParentFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetParentFolders.gql
{
  "folderId": "{{folderId}}"
}

###

# @name GetPublishedFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetPublishedFolders.json

###

# @name GetPublishedFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetPublishedFolders.gql
{
  "first": 4,
  "after": null,
  "parentFolderId": "{{parentFolderId}}",
  "source": "ACTIVE",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    {
      "type": "CREATED_BY_ME"
    }
  ],
  "timeRange": null
}

###

# @name GetLooms.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetLooms.json

###

# @name GetLooms.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetLooms.gql
{
  "limit": 12,
  "cursor": null,
  "folderId": "{{folderId}}",
  "source": "ALL",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    [
      {
        "type": "CREATED_BY_ME"
      }
    ],
    [
      {
        "type": "NOT_IN_FOLDER"
      }
    ]
  ],
  "timeRange": null
}
