# @name GetParentFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetParentFolders.json

###

# @name GetParentFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetParentFolders.gql
{
  "folderId": "{{folderId}}"
}

###

# @name GetPublishedFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetPublishedFolders.json

###

# @name GetPublishedFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetPublishedFolders.gql
{
  "first": 4,
  "after": null,
  "parentFolderId": "{{parentFolderId}}",
  "source": "ACTIVE",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    {
      "type": "CREATED_BY_ME"
    }
  ],
  "timeRange": null
}

###

# @name GetLooms.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetLooms.json

###

# @name GetLooms.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetLooms.gql
{
  "limit": 12,
  "cursor": null,
  "folderId": "{{folderId}}",
  "source": "ALL",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    [
      {
        "type": "CREATED_BY_ME"
      }
    ],
    [
      {
        "type": "NOT_IN_FOLDER"
      }
    ]
  ],
  "timeRange": null
}

###

# @name GetUserByIdWithProfile.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetUserByIdWithProfile.json

###

# @name GetUserByIdWithProfile.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetUserByIdWithProfile.gql
{
  "userId": {{userId}}
}

###

# @name createFolder.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/createFolder.json

###

# @name createFolder.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/createFolder.gql
{
  "name": "from Loop",
  "parentFolderId": "{{parentFolderId}}",
  "visibility": "owner"
}

###

# @name BulkDeleteFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/BulkDeleteFolders.json

###

# @name BulkDeleteFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/BulkDeleteFolders.gql
{
  "folderIds": [
    "{{folderIdToDelete}}"
  ]
}

###

# @name MoveFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/MoveFolders.json

###

# @name MoveFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/MoveFolders.gql
{
  "folderIds": [
    "{{folderIdToMove}}"
  ],
  "newParentFolderId": "{{parentFolderId}}",
  "spaceId": "{{spaceId}}",
  "workspaceId": {{workspaceId}}
}

###

# @name GetMySpaceMemberships.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/GetMySpaceMemberships.json

###

# @name GetMySpaceMemberships.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/GetMySpaceMemberships.gql
{
  "first": 20
}

###

# @name RenameFolder.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/RenameFolder.json

###

# @name RenameFolder.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/RenameFolder.gql
{
  "folderId": "{{folderIdToRename}}",
  "name": "from Loop II"
}

###

# @name ArchiveFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< json/ArchiveFolders.json

###

# @name ArchiveFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< graphql/ArchiveFolders.gql
{
  "folderIds": [
    "{{folderIdToArchive}}"
  ],
  "isArchived": true
}
