# @name GetParentFolders.json
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

[
  {
    "operationName": "GetParentFolders",
    "variables": {
      "folderId": "{{folderId}}"
    },
    "query": "query GetParentFolders($folderId: ID!) {\n  getParentFolders(folderId: $folderId) {\n    __typename\n    ... on GetParentFoldersPayload {\n      currentFolder {\n        id\n        owner_id\n        name\n        visibility\n        totalNestedVideos\n        currentUserCanEdit\n        hasDuplicateInSpaces\n        __typename\n      }\n      parentFolders {\n        id\n        name\n        __typename\n      }\n      __typename\n    }\n  }\n}\n"
  }
]

###

# @name GetParentFolders.gql
# @no-cookie-jar
# @no-log
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

query GetParentFolders($folderId: ID!) {
    getParentFolders(folderId: $folderId) {
        __typename
        ... on GetParentFoldersPayload {
            currentFolder {
                id
                owner_id
                name
                visibility
                totalNestedVideos
                currentUserCanEdit
                hasDuplicateInSpaces
                __typename
            }
            parentFolders {
                id
                name
                __typename
            }
            __typename
        }
    }
}
{
  "folderId": "{{folderId}}"
}
