//
// Working with workspace and users.
//

###

# @name userWorkspaceMemberships.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/userWorkspaceMemberships.gql
{}
>> loom/responses/userWorkspaceMemberships.json

###

# @name userWorkspaceMemberships.any.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/userWorkspaceMemberships.any.json
>> loom/responses/userWorkspaceMemberships.json

###

# @name GetUserByIdWithProfile.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetUserByIdWithProfile.gql
{
  "userId": {{userId}}
}
>> loom/responses/GetUserByIdWithProfile.json

###

# @name GetUserByIdWithProfile.root,archive.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetUserByIdWithProfile.root,archive.json
>> loom/responses/GetUserByIdWithProfile.json

###

//
// Working with spaces.
//

###

# @name CreateSpace.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/CreateSpace.gql
{
  "name": "Loop",
  "privacy": "workspace",
  "userIds": [
    "{{userId}}"
  ],
  "analyticsSource": "sidebar"
}
>> loom/responses/CreateSpace.json

###

# @name CreateSpace.private.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/CreateSpace.private.json
>> loom/responses/CreateSpace.json

###

# @name getOpenSpaces.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/getOpenSpaces.gql
{
  "first": 15
}
>> loom/responses/getOpenSpaces.json

###

# @name getOpenSpaces.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/getOpenSpaces.json
>> loom/responses/getOpenSpaces.json

###

# @name GetMySpaceMemberships.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetMySpaceMemberships.gql
{
  "first": 20
}
>> loom/responses/GetMySpaceMemberships.json

###

# @name GetMySpaceMemberships.any.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetMySpaceMemberships.any.json
>> loom/responses/GetMySpaceMemberships.json

###

# @name GetMyClosedSpaceMemberships.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetMyClosedSpaceMemberships.gql
{
  "first": 15
}
>> loom/responses/GetMyClosedSpaceMemberships.json

###

# @name GetMyClosedSpaceMemberships.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetMyClosedSpaceMemberships.json
>> loom/responses/GetMyClosedSpaceMemberships.json

###

# @name GetWorkspaceArchivedSpaces.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetWorkspaceArchivedSpaces.gql
{
  "first": 1000
}
>> loom/responses/GetWorkspaceArchivedSpaces.json

###

# @name GetWorkspaceArchivedSpaces.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetWorkspaceArchivedSpaces.json
>> loom/responses/GetWorkspaceArchivedSpaces.json

###

# @name GetSpaceNameAndMembers.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetSpaceNameAndMembers.gql
{
  "spaceId": "{{spaceId}}",
  "first": 5
}
>> loom/responses/GetSpaceNameAndMembers.json

###

# @name GetSpaceNameAndMembers.space.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetSpaceNameAndMembers.space.json
>> loom/responses/GetSpaceNameAndMembers.json

###

# @name ArchiveSpace.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/ArchiveSpace.gql
{
  "spaceId": "{{spaceId}}"
}
>> loom/responses/ArchiveSpace.json

###

# @name ArchiveSpace.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/ArchiveSpace.json
>> loom/responses/ArchiveSpace.json

###

# @name UnarchiveSpace.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/UnarchiveSpace.gql
{
  "spaceId": "{{spaceId}}"
}
>> loom/responses/UnarchiveSpace.json

###

# @name UnarchiveSpace.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/UnarchiveSpace.json
>> loom/responses/UnarchiveSpace.json

###

# @name JoinSpace.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/JoinSpace.gql
{
  "spaceId": "{{spaceId}}",
  "analyticsSource": "browse"
}
>> loom/responses/JoinSpace.json

###

# @name JoinSpace.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/JoinSpace.json
>> loom/responses/JoinSpace.json

###

# @name LeaveSpace.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/LeaveSpace.gql
{
  "spaceId": "{{spaceId}}",
  "analyticsSource": "space_page"
}
>> loom/responses/LeaveSpace.json

###

# @name LeaveSpace.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/LeaveSpace.json
>> loom/responses/LeaveSpace.json

###

//
// Working with folder structure.
//

###

# @name GetParentFolders.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetParentFolders.gql
{
  "folderId": "{{folderId}}"
}
>> loom/responses/GetParentFolders.json

###

# @name GetParentFolders.any.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetParentFolders.any.json
>> loom/responses/GetParentFolders.json

###

# @name GetPublishedFolders.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetPublishedFolders.gql
{
  "first": 4,
  "after": null,
  "parentFolderId": "{{parentFolderId}}",
  "source": "ACTIVE",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    {
      "type": "CREATED_BY_ME"
    }
  ],
  "timeRange": null
}
>> loom/responses/GetPublishedFolders.json

###

# @name GetPublishedFolders.root.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetPublishedFolders.root.json
>> loom/responses/GetPublishedFolders.json

###

//
// Working with folders.
//

###

# @name createFolder.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/createFolder.gql
{
  "name": "Loop",
  "parentFolderId": "{{parentFolderId}}",
  "visibility": "owner"
}
>> loom/responses/createFolder.json

###

# @name createFolder.root.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/createFolder.root.json
>> loom/responses/createFolder.json

###

# @name RenameFolder.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/RenameFolder.gql
{
  "folderId": "{{folderIdToRename}}",
  "name": "Loop"
}
>> loom/responses/RenameFolder.json

###

# @name RenameFolder.any.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/RenameFolder.any.json
>> loom/responses/RenameFolder.json

###

# @name MoveFolders.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/MoveFolders.gql
{
  "folderIds": [
    "{{folderIdToMove}}"
  ],
  "newParentFolderId": "{{parentFolderId}}",
  "spaceId": "{{spaceId}}",
  "workspaceId": {{workspaceId}}
}
>> loom/responses/MoveFolders.json

###

# @name MoveFolders.root.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/MoveFolders.root.json
>> loom/responses/MoveFolders.json

###

# @name ArchiveFolders.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/ArchiveFolders.gql
{
  "folderIds": [
    "{{folderIdToArchive}}"
  ],
  "isArchived": true
}
>> loom/responses/ArchiveFolders.json

###

# @name ArchiveFolders.root.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/ArchiveFolders.root.json
>> loom/responses/ArchiveFolders.json

###

# @name BulkDeleteFolders.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/BulkDeleteFolders.gql
{
  "folderIds": [
    "{{folderIdToDelete}}"
  ]
}
>> loom/responses/BulkDeleteFolders.json

###

# @name BulkDeleteFolders.any.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/BulkDeleteFolders.any.json
>> loom/responses/BulkDeleteFolders.json

###

//
// Working with looms.
//

###

# @name GetLooms.gql
# @no-cookie-jar
# @no-redirect
GRAPHQL {{host}}/graphql
cookie: connect.sid={{sid}}

< loom/graphql/GetLooms.gql
{
  "limit": 12,
  "cursor": null,
  "folderId": "{{folderId}}",
  "source": "ALL",
  "sortOrder": "DESC",
  "sortType": "RECENT",
  "filters": [
    [
      {
        "type": "CREATED_BY_ME"
      }
    ],
    [
      {
        "type": "NOT_IN_FOLDER"
      }
    ]
  ],
  "timeRange": null
}
>> loom/responses/GetLooms.json

###

# @name GetLooms.root.json
# @no-cookie-jar
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

< loom/json/GetLooms.root.json
>> loom/responses/GetLooms.json

###

//
// Reverse engineering.
//

###

# @name first look
# @no-cookie-jar
# @no-log
# @no-redirect
POST {{host}}/graphql
content-type: application/json
cookie: connect.sid={{sid}}

###
